### ISSUE TITLE
about libMNNExpress.so

### ISSUE THREAD

**Issue by leemengxing** [MirrorYuChen/MNN_test#1]
你好，我问一下libMNNExpress.so这个文件在编译MNN的什么位置。为什么我没有找到呢，是否这个共享库为必须的？望回复。

**Comment by 1976277169** [comment]
这个不是必须的，具体路径我回家看看给你回复~

**Comment by leemengxing** [comment]
ok，我安卓和liux都编完成，都找不到这个库。可能是哪个选项没开吧。

**Comment by leemengxing** [comment]
给你点个star，现在MNN资料真不多见。

**Comment by MirrorYuChen** [comment]
好的，谢谢，后期学习会继续更新~

**Comment by leemengxing** [comment]
我c++很早不用了，关键点pfld：：impl是什么语法？内部类，匿名类吗？

**Comment by 1976277169** [comment]
一个简单的封装，可以去看一下我csdn博客里面的说明~

**Comment by MirrorYuChen** [comment]
路径在build->express文件夹里面~
