### ISSUE TITLE
make的时候报错了

### ISSUE THREAD

**Issue by lth611798** [MirrorYuChen/MNN_test#3]
[  6%] Building CXX object CMakeFiles/blazeface.dir/src/detect.cpp.o
[ 13%] Building CXX object CMakeFiles/blazeface.dir/include/mnn/tools/cpp/revertMNNModel.cpp.o
[ 20%] Building CXX object CMakeFiles/blazeface.dir/src/pfld.cpp.o
[ 26%] Building CXX object CMakeFiles/blazeface.dir/src/blazeface.cpp.o
[ 33%] Linking CXX executable blazeface
../lib/libMNN.so: 无法添加符号: 文件格式错误
collect2: error: ld returned 1 exit status
CMakeFiles/blazeface.dir/build.make:189: recipe for target 'blazeface' failed
make[2]: *** [blazeface] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/blazeface.dir/all' failed
make[1]: *** [CMakeFiles/blazeface.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MirrorYuChen** [comment]
你需要将你那边编译好的mnn库替换掉我这个项目下mnn库~不同平台环境下编译的会有差别，我这个是在jetson nano下编译的~

**Comment by lth611798** [comment]
已解决！

**Comment by MirrorYuChen** [comment]
给star啊老哥，不准白嫖，哈哈哈哈~
